name: augmented_anatomy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  arcore_flutter_plugin: ^0.1.0
  vector_math: ^2.1.4
  connectivity: ^3.0.6
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
  fonts:
    - family: Nunito Sans
      fonts:
        - asset: fonts/NunitoSans-Bold.ttf
        - asset: fonts/NunitoSans-Light.ttf
        - asset: fonts/NunitoSans-SemiBold.ttf
        - asset: fonts/NunitoSans-Regular.ttf

